name: Imbee-Notification-CI

on: 
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.2
      - name: Intall package
        working-directory: ./src
        run: |
          poetry install
          echo "run python test"

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    needs: [test]
    steps:
      - name: Run Build ECR
        run: bash ./devops/build-ecr.sh

  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    needs: [build]
    steps:
      - name: Migrate Database
        run: bash ./devops/merge.sh

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env: 
        # please set secret key in your repo
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
