name: Imbee-Notification-Migrate

on: 
  push:
    branches: [ ManualTrigger ]
  pull_request: 
    branches: [ ManualTrigger ]

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Migrate Database
        run: bash ./devops/merge.sh