name: Imbee-Notification-CI

on: 
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.15'
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.2
      - name: Intall package
        working-directory: ./src
        run: |
          poetry install
          echo "run python test"
